# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-22 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobmodel',
            table='GENERICPARSER_JOB',
        ),
        migrations.AlterModelTable(
            name='jobstatusmodel',
            table='GENERICPARSER_JOB_STATUS',
        ),
        migrations.AlterModelTable(
            name='nsdmsubscriptionmodel',
            table='GENERICPARSER_NSDM_SUBSCRIPTION',
        ),
        migrations.AlterModelTable(
            name='nspackagemodel',
            table='GENERICPARSER_NSPACKAGE',
        ),
        migrations.AlterModelTable(
            name='pnfpackagemodel',
            table='GENERICPARSER_PNFPACKAGE',
        ),
        migrations.AlterModelTable(
            name='servicepackagemodel',
            table='GENERICPARSER_SERVICEPACKAGE',
        ),
        migrations.AlterModelTable(
            name='softwareimagemodel',
            table='GENERICPARSER_SOFTWAREIMAGEMODEL',
        ),
        migrations.AlterModelTable(
            name='vnfpackagemodel',
            table='GENERICPARSER_VNFPACKAGE',
        ),
    ]
